apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-serviceaccount
  annotations:
    azure.workload.catalog/client-id: 71903bb7-639e-4f0b-a2d9-f538c283082d
  labels:
    azure.workload.catalog/use: "true"
